version: '3.6'

services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    image: flutter_dev
    container_name: flutter_dev_cont
    working_dir: /usr/src/app
    network_mode: "host"
    privileged: true
    #command: bash -c "code ."
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /dev/bus/usb:/dev/bus/usb
      - .vscode:/home/dev/.vscode
      - ../azarja_app:/usr/src/app
    tty: true